### ISSUE TITLE
Insert modules

### ISSUE THREAD

**Issue by dida-code** [alexkdeveloper/calculator#1]
Hello Alex, can you tell me how to import models like matplotlib and numpy.. I tried using your manifest example where I changed the url and SHA 256 but it always gives me an error. I haven't found a good example anywhere. i need these models to make diagrams..

**Comment by alexkdeveloper** [comment]
Hi!
Try to do as here:
https://github.com/Sjoerd1993/Graphs/blob/main/python-dependencies.json

**Comment by dida-code** [comment]
Thanks, it helped me
