### ISSUE TITLE
Basic sum (28) got "1.0" as result

### ISSUE THREAD

**Issue by MarArMar** [alexkdeveloper/calculator#3]
"1 + 1 + 1 + 1 + 1 + 1 + 1 + 2 + 2 + 1 + 0 + 0 + 1 + 1 + 1 + 2 + 3 + 3 + 2 + 2 + 1 = 1.0"

Result is supposed to be 28

![image](https://github.com/alexkdeveloper/calculator/assets/136232300/7308128a-7bb7-4ffe-b093-b2d0dddbc230)

**Comment by MarArMar** [comment]
I also posted an issue at "StringCalculator" lib

https://github.com/idozahavy/StringCalculator/issues/1

**Comment by alexkdeveloper** [comment]
The arithmetic expression must be entered without spaces. Then everything is calculated normally:
![Снимок экрана от 2024-04-29 11-00-13](https://github.com/alexkdeveloper/calculator/assets/73014273/17c06ee9-e70b-4c20-a058-bcf52c5f35f5)

**Comment by alexkdeveloper** [comment]
In the next release of the application, the spaces will be removed automatically. The corresponding changes have already been added to the repository.

**Comment by alexkdeveloper** [comment]
The new version of the program will be available in a few hours.

**Comment by MarArMar** [comment]
So great, thank you very much

**Comment by MarArMar** [comment]
Perfect, I just tested it, it works ! 🎉 

thanks again for this very practical app !
