### ISSUE TITLE
Calculus with wrong result : should be 3525, is 0

### ISSUE THREAD

**Issue by MarArMar** [alexkdeveloper/calculator#5]
`"((48*83) +(73*42)) / 2" got "0" as a result`

![image](https://github.com/alexkdeveloper/calculator/assets/136232300/94c4eea8-a527-46cd-ba12-aa8ba1880c64)

**Comment by alexkdeveloper** [comment]
Internal brackets are not needed. If you enter without them, then everything is calculated correctly. 

Although I agree that there is a problem, but most likely it lies in the library code. It is better to contact the library developer with such questions.
![Снимок экрана от 2024-05-14 14-36-26](https://github.com/alexkdeveloper/calculator/assets/73014273/b32e5815-1239-4ffb-91f4-09c19683f75a)

**Comment by MarArMar** [comment]
Ok I posted the issue to the lib dev 👍

**Comment by alexkdeveloper** [comment]
Hi.

A new version of the StringCalculator library has been released.
But the developer did not publish the source code archive I needed in the Python package index. 

I need it to create an application with a new version.

I have opened the corresponding task in the repository, but have not received a response yet.

**Comment by MarArMar** [comment]
Cool, thanks for the update 😊

Yeah I think they fixed it they mentioned the issue in a commit

**Comment by alexkdeveloper** [comment]
I haven't updated anything yet, as the archive with the new version of the library is still unavailable:
https://pypi.org/project/StringCalculator/0.0.5/#files
The application is still using version 0.0.4.

**Comment by MarArMar** [comment]
Yes but I meant you "updated" this issue with the news/current state of affairs, and thanks for that 😉

**Comment by alexkdeveloper** [comment]
Hi!

Quite a long time has passed, and the archives for the new version of the library are still unavailable.

https://pypi.org/project/StringCalculator/0.0.5/#files

If the developer does not add archives to the Python package index in the near future, then I can try to include this library in my application. That is, the manifest will no longer refer to a specific version of the library. All this will be included in the application itself.

**Comment by alexkdeveloper** [comment]
I still hope that the developer will add the source code archives to the Python package index in the near future.
